### ISSUE TITLE
Ingress in Helm chart broken

### ISSUE THREAD

**Issue by as42sl** [airbytehq/helm-charts#2] opened 2022-09-15 12:57 UTC
Activating the ingress breaks the helm chart:

`{"level":"error","ts":"2022-09-15T12:52:48.137Z","msg":"reconciliation failed: Helm upgrade failed: template: airbyte/charts/webapp/templates/ingress.yaml:53:33: executing \"airbyte/charts/webapp/templates/ingress.yaml\" at <.Release.Name>: nil pointer evaluating interface {}.Name","name":"airbyte","namespace":"data-warehouse-airbyte","reconciler kind":"HelmRelease","annotations":{"helm.toolkit.fluxcd.io/revision":"0.40.6"}}`

Test with: webapp.ingress.enabled: true

It used to work with v '0.41.0'

**Comment by as42sl** [comment] 2022-09-15 13:10
Here is the culprit: https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-webapp/templates/ingress.yaml#L53
It should be `{{ $.Release.Name }}` instead of`{{ .Release.Name }}` because it is inside a range

**Comment by NipunaPrashan** [comment] 2022-09-16 01:07
Yes, I also can reproduce the issue. Same issue

**Comment by DoctahPopp871** [comment] 2022-09-20 16:00
I would suggest rather than using `{{ .Release.Name }}` here simply using the existing `$fullName` variable that is being used elsewhere. The `$fullName` variable already uses the `{{.Release.Name}} to define itself. 

This gets around the scoping limitation within the range function.  

So the fix is `{{ $fullName }}-airbyte-webapp-svc` on ln 53 of the ingress file. I can make an MR.

**Comment by DoctahPopp871** [comment] 2022-09-21 00:36
I think we actually want `{{ $.Release.Name }}-{{ $fullName }}-svc`

**Comment by koconder** [comment] 2022-09-28 01:06
Fix is in here https://github.com/airbytehq/airbyte/pull/16931 pending release to artifacthub

**Comment by KqLLL** [comment] 2022-09-29 06:44
Please fix this bug on release [0.41.2](https://github.com/airbytehq/helm-charts/commit/4d8e0f2671e00587ce9cd0e73df0e9bc71d68487)

It works on 0.41.1

**Comment by KqLLL** [comment] 2022-09-30 06:18
> Please fix this bug on release [0.41.2](https://github.com/airbytehq/helm-charts/commit/4d8e0f2671e00587ce9cd0e73df0e9bc71d68487)
> 
> It works on 0.41.1

@xpuska513

**Comment by xpuska513** [comment] 2022-10-05 12:31
Hi!
All changes were published in 0.40.17, sorry for confusion with versioning it's due to active changes in the release process itself.
Once I'm back from vac I'll put some thing on discussion about separating helm-charts source code into this repo.

**Comment by davinchia** [comment] 2023-04-13 22:15
Closed as out of date.

**Closed** 2023-04-13 22:15 UTC
